# -*- coding: utf-8 -*-
"""HR Employee Attrition Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2sUhsHnmFTnR26_iVhkJkhsTTWqlINu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('/content/HR Employee Attrition Analysis.xltx')

"""3. Data Understanding"""

df.head()

# ukuran data
df.shape

#Kolom nama
df.columns.tolist()

#informasi dataset
df.info()

#deskriptif
df.describe().T

#statistik kolom kategorikal
df.describe(include='object').T

"""4. Missing Values"""

df.isnull().sum()

df.duplicated().sum()

#Cek unik value
for col in df.select_dtypes(include='object').columns:
    print(f'\n{col}')
    print(df[col].value_counts())

#cek kolom konstan
constant_cols = [
    col for col in df.columns
    if df[col].nunique() == 1
]

constant_cols

"""kolom tersebut tidak memberikan variasi informasi untuk analisis."""

df = df.drop(columns=constant_cols)

# cek outlier
df[['Age',
    'MonthlyIncome',
    'TotalWorkingYears',
    'YearsAtCompany']].describe()

# Boxplot
plt.figure(figsize=(8, 5))
plt.boxplot(df['MonthlyIncome'])
plt.title('Monthly Income Distribution')
plt.ylabel('Monthly Income')
plt.show()

# Calculate IQR
Q1 = df['MonthlyIncome'].quantile(0.25)
Q3 = df['MonthlyIncome'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

income_outliers = df[
    (df['MonthlyIncome'] < lower_bound) |
    (df['MonthlyIncome'] > upper_bound)
]

print("Total Outliers:", len(income_outliers))

income_outliers[
    ['MonthlyIncome', 'JobRole', 'JobLevel', 'YearsAtCompany', 'TotalWorkingYears']
].sort_values('MonthlyIncome', ascending=False).head(20)

"""Outliers were identified in Monthly Income using the IQR method. However, these values were retained because they represent plausible salary differences across job roles and seniority levels rather than data errors.

Feature Engineering
"""

# Attrition FLag
df['AttritionFlag'] = df['Attrition'].map({
    'Yes': 1,
    'No': 0
})

# AGe Grup
df['AgeGroup'] = pd.cut(
    df['Age'],
    bins=[0, 25, 35, 45, 55, 100],
    labels=[
        '<25',
        '25-34',
        '35-44',
        '45-54',
        '55+'
    ],
    right=False
)

# income grup
df['IncomeGroup'] = pd.qcut(
    df['MonthlyIncome'],
    q=4,
    labels=[
        'Low',
        'Lower-Middle',
        'Upper-Middle',
        'High'
    ]
)

# Tanure grup
df['TenureGroup'] = pd.cut(
    df['YearsAtCompany'],
    bins=[-1, 2, 5, 10, 20, float('inf')],
    labels=[
        '0-2 Years',
        '3-5 Years',
        '6-10 Years',
        '11-20 Years',
        '20+ Years'
    ]
)

"""Cek Hasil Cleaning barusan"""

df.info()

df.head()

df.isnull().sum().sort_values(ascending=False).head(10)

df.shape

"""EDA"""

#OVERALL Attrition
df['Attrition'].value_counts()

# Attrition by Departemen
department_attrition = pd.crosstab(
    df['Department'],
    df['Attrition'],
    normalize='index'
) * 100

department_attrition

# Attretion by Job Role
job_attrition = (
    df.groupby('JobRole')['AttritionFlag']
    .agg(['count', 'sum', 'mean'])
)

job_attrition['mean'] = job_attrition['mean'] * 100

job_attrition.sort_values(
    'mean',
    ascending=False
)

# Attrition by overtime
overtime_attrition = (
    df.groupby('OverTime')['AttritionFlag']
    .mean() * 100
)

overtime_attrition

# Attrition by age
age_attrition = (
    df.groupby(
        'AgeGroup',
        observed=False
    )['AttritionFlag']
    .mean() * 100
)

age_attrition

# Attretion by Income Group
income_attrition = (
    df.groupby(
        'IncomeGroup',
        observed=False
    )['AttritionFlag']
    .mean() * 100
)

income_attrition

# Attrition by Tenure
tenure_attrition = (
    df.groupby(
        'TenureGroup',
        observed=False
    )['AttritionFlag']
    .mean() * 100
)

tenure_attrition

# job satification
satisfaction_attrition = (
    df.groupby('JobSatisfaction')['AttritionFlag']
    .mean() * 100
)

satisfaction_attrition

# work life balance
wlb_attrition = (
    df.groupby('WorkLifeBalance')['AttritionFlag']
    .mean() * 100
)

wlb_attrition

# business travel
travel_attrition = (
    df.groupby('BusinessTravel')['AttritionFlag']
    .mean() * 100
)

travel_attrition

# Select numerical columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Calculate correlation
correlation_matrix = numeric_df.corr()

correlation_matrix

import seaborn as sns

plt.figure(figsize=(18, 14))

sns.heatmap(
    correlation_matrix,
    cmap='coolwarm',
    center=0,
    linewidths=0.5
)

plt.title('Correlation Matrix of Numerical Features')
plt.show()

# Export clean dataset
df.to_excel(
    'HR_Employee_Attrition_Clean.xlsx',
    index=False
)

from google.colab import files
files.download('HR_Employee_Attrition_Clean.xlsx')

#Attrition Distribution

plt.figure(figsize=(7, 5))

attrition_counts = df['Attrition'].value_counts()

plt.bar(
    attrition_counts.index,
    attrition_counts.values
)

plt.title('Employee Attrition Distribution')
plt.xlabel('Attrition')
plt.ylabel('Number of Employees')

plt.show()

#Attrition Rate by Departement

plt.figure(figsize=(7, 5))

attrition_counts = df['Attrition'].value_counts()

bars = plt.bar(
    attrition_counts.index,
    attrition_counts.values
)

plt.title('Employee Attrition Distribution')
plt.xlabel('Attrition')
plt.ylabel('Number of Employees')

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        f'{int(bar.get_height()):,}',
        ha='center',
        va='bottom'
    )

plt.show()

plt.figure(figsize=(8, 5))

bars = plt.barh(
    department_attrition.index,
    department_attrition.values
)

plt.title('Attrition Rate by Department')
plt.xlabel('Attrition Rate (%)')
plt.ylabel('Department')

plt.gca().invert_yaxis()

for bar in bars:
    plt.text(
        bar.get_width() + 0.3,
        bar.get_y() + bar.get_height()/2,
        f'{bar.get_width():.1f}%',
        va='center'
    )

plt.show()

#Attrition Rate by Job Role

plt.figure(figsize=(10, 6))

bars = plt.barh(
    jobrole_attrition.index,
    jobrole_attrition.values
)

plt.title('Attrition Rate by Job Role')
plt.xlabel('Attrition Rate (%)')
plt.ylabel('Job Role')

plt.gca().invert_yaxis()

for bar in bars:
    plt.text(
        bar.get_width() + 0.3,
        bar.get_y() + bar.get_height()/2,
        f'{bar.get_width():.1f}%',
        va='center'
    )

plt.show()

#Attrition Rate by Overtime

plt.figure(figsize=(7, 5))

bars = plt.bar(
    overtime_attrition.index,
    overtime_attrition.values
)

plt.title('Attrition Rate by Overtime')
plt.xlabel('Overtime')
plt.ylabel('Attrition Rate (%)')

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.5,
        f'{bar.get_height():.1f}%',
        ha='center'
    )

plt.show()

#Attrition Rate by Age Group

plt.figure(figsize=(9, 5))

bars = plt.bar(
    age_attrition.index.astype(str),
    age_attrition.values
)

plt.title('Attrition Rate by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Attrition Rate (%)')

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.3,
        f'{bar.get_height():.1f}%',
        ha='center'
    )

plt.show()

# Attrition Rate by Tenure

plt.figure(figsize=(9, 5))

bars = plt.bar(
    tenure_attrition.index.astype(str),
    tenure_attrition.values
)

plt.title('Attrition Rate by Tenure Group')
plt.xlabel('Tenure Group')
plt.ylabel('Attrition Rate (%)')

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.3,
        f'{bar.get_height():.1f}%',
        ha='center'
    )

plt.show()

#Attrition Rate by Income Group

plt.figure(figsize=(9, 5))

bars = plt.bar(
    income_attrition.index.astype(str),
    income_attrition.values
)

plt.title('Attrition Rate by Income Group')
plt.xlabel('Income Group')
plt.ylabel('Attrition Rate (%)')

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 0.3,
        f'{bar.get_height():.1f}%',
        ha='center'
    )

plt.show()

